name: pytorch-cuda-env
channels:
  - anaconda
  - defaults
  - conda-forge
  - comet_ml
  - pytorch
  - nvidia
dependencies:
  - python==3.8.10
  - numpy
  - pytorch==1.9.0
  - torchaudio
  - cudatoolkit==${CUDA_TOOLKIT_VERSION}
  - scikit-learn
  - pyyaml
  - comet_ml
  - optuna
  - pydub
  - librosa
  - pandas
  - pip
  - pip:
    - torchsummary
